import type { ElementType } from 'react';
import { ArrowRight, BarChart3, BellRing, CalendarDays, Check, Database, Link2, LockKeyhole, QrCode, ShieldCheck, Users2, Webhook } from 'lucide-react';
import { Logo } from '@/components/logo';
import { ThemeToggle } from '@/components/theme-toggle';
import { appointments as demoAppointments, metrics as demoMetrics, webhookEvents } from '@/lib/data';
import { getDashboard } from '@/lib/dashboard';

export const dynamic = 'force-dynamic';

const features = ['Links personalizados por consultor ou campanha','Calendário interativo com bloqueio de conflitos','Confirmação automática com protocolo e QR Code','CRM integrado com funil de visita até venda','Lembretes por WhatsApp, SMS e E-mail','Relatórios exportáveis em PDF, Excel e CSV'];
const roles = ['Administrador','Gerente','Supervisor','Consultor'];

export default async function Home() {
  const dashboard = await getDashboard(process.env.DEMO_COMPANY_ID).catch(() => null);
  const metrics = dashboard ? [
    { label: 'Total de agendamentos', value: String(dashboard.total), delta: 'real', icon: CalendarDays },
    { label: 'Agendamentos hoje', value: String(dashboard.todayCount), delta: 'hoje', icon: BarChart3 },
    { label: 'Cancelamentos', value: String(dashboard.cancellations), delta: 'real', icon: ShieldCheck },
    { label: 'Taxa de comparecimento', value: `${dashboard.attendanceRate}%`, delta: 'real', icon: Check },
  ] : demoMetrics;
  const agenda = dashboard?.upcoming.map((item) => ({ time: item.startsAt.toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' }), client: item.client.fullName, status: item.status, origin: item.bookingLink.name, consultant: item.user?.name ?? 'Equipe' })) ?? demoAppointments;

  return <main className="min-h-screen"><header className="sticky top-0 z-50 border-b border-zinc-200/80 bg-white/80 backdrop-blur dark:border-zinc-800 dark:bg-zinc-950/80"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><Logo/><nav className="hidden gap-6 text-sm text-zinc-600 dark:text-zinc-300 md:flex"><a href="#dashboard">Dashboard</a><a href="#links">Links</a><a href="#api">API</a><a href="/visita-metrocasa">Página pública</a></nav><div className="flex items-center gap-3"><ThemeToggle/><a className="hidden rounded-full border border-zinc-200 px-4 py-2 text-sm font-semibold dark:border-zinc-800 sm:inline-flex" href="/login">Entrar</a><a className="rounded-full bg-zinc-950 px-4 py-2 text-sm font-semibold text-white dark:bg-white dark:text-zinc-950" href="/register">Criar conta</a></div></div></header>
<section className="grid-bg border-b border-zinc-200 dark:border-zinc-800"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-20 lg:grid-cols-[1fr_520px] lg:items-center"><div><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-zinc-200 bg-white px-3 py-1 text-sm text-zinc-600 shadow-sm dark:border-zinc-800 dark:bg-zinc-900 dark:text-zinc-300"><span className="h-2 w-2 rounded-full bg-atto-red"/> SaaS multiempresa para visitas comerciais</div><h1 className="text-5xl font-black tracking-tight md:text-7xl">Agendamentos comerciais com a precisão de uma operação moderna.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-zinc-600 dark:text-zinc-300">ATTO AGENDA permite que corretores, vendedores e empresas criem links como <strong>agenda.sistema.com/connor</strong> ou <strong>/visita-metrocasa</strong>, capturem leads e confirmem visitas automaticamente.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a className="inline-flex items-center justify-center gap-2 rounded-xl bg-atto-red px-5 py-3 font-bold text-white" href="/visita-metrocasa">Testar agendamento <ArrowRight size={18}/></a><a className="inline-flex items-center justify-center rounded-xl border border-zinc-200 px-5 py-3 font-bold dark:border-zinc-800" href="#dashboard">Abrir dashboard</a></div></div><DashboardPreview agenda={agenda}/></div></section>
<section id="dashboard" className="mx-auto max-w-7xl px-5 py-16"><div className="mb-8 flex items-end justify-between"><div><p className="font-bold text-atto-red">Dashboard em tempo real</p><h2 className="text-3xl font-black tracking-tight">Métricas, próximas visitas e status</h2></div><p className="text-sm text-zinc-500">Fonte: <strong className="text-atto-green">{dashboard ? 'JSON/Google Sheets' : 'demo local'}</strong></p></div><div className="grid gap-4 md:grid-cols-4">{metrics.map(({label,value,delta,icon:Icon})=><div key={label} className="rounded-2xl border border-zinc-200 bg-white p-5 shadow-soft dark:border-zinc-800 dark:bg-zinc-900"><Icon className="mb-4 text-atto-red"/><p className="text-sm text-zinc-500">{label}</p><div className="mt-2 flex items-end justify-between"><strong className="text-3xl">{value}</strong><span className="text-sm text-atto-green">{delta}</span></div></div>)}</div><div className="mt-4 grid gap-4 lg:grid-cols-[1.4fr_.8fr]"><Agenda agenda={agenda}/><StatusPanel statuses={dashboard?.byStatus}/></div></section>
<section id="links" className="border-y border-zinc-200 bg-zinc-50 py-16 dark:border-zinc-800 dark:bg-zinc-950"><div className="mx-auto grid max-w-7xl gap-6 px-5 lg:grid-cols-3"><Feature icon={Link2} title="Geração de links" text="CRUD completo por API: criar, editar, ativar/desativar, slug único, endereço, duração, limite diário, dias e horários."/><Feature icon={CalendarDays} title="Disponibilidade inteligente" text="Bloqueia horários reservados, links inativos, datas expiradas, conflitos e horários fora da disponibilidade."/><Feature icon={BellRing} title="Automações" text="Base pronta para lembretes 24h, 3h e 1h antes via WhatsApp, SMS e E-mail."/>{features.map(f=><div key={f} className="flex gap-3 rounded-2xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><Check className="mt-1 shrink-0 text-atto-green" size={18}/><span>{f}</span></div>)}</div></section>
<section className="mx-auto grid max-w-7xl gap-6 px-5 py-16 lg:grid-cols-3"><Feature icon={Users2} title="Admin e permissões" text={`Modelo multiempresa com Company, User e perfis: ${roles.join(', ')}.`}/><Feature icon={Database} title="Banco de dados" text="Persistência por Google Sheets em produção e JSON local somente em desenvolvimento."/><Feature icon={ShieldCheck} title="Segurança LGPD Ready" text="Validação server-side com Zod, escopo por companyId, rate limit público e auditoria."/><Feature icon={QrCode} title="Comprovante e protocolo" text="Cada visita recebe protocolo AG-2026-000000 e status inicial scheduled."/><Feature icon={Webhook} title="API REST" text={`CRUD de appointments e booking-links, além de rotas públicas. Eventos planejados: ${webhookEvents.join(', ')}.`}/><Feature icon={LockKeyhole} title="Calendários nativos" text="Arquitetura preparada para Google Calendar, Outlook Calendar e Apple Calendar."/></section>
<section id="api" className="mx-auto max-w-7xl px-5 pb-20"><div className="rounded-3xl bg-zinc-950 p-6 text-white shadow-soft"><p className="text-sm text-zinc-400">API funcional com escopo multiempresa</p><pre className="mt-4 overflow-x-auto text-sm"><code>{`GET/POST /api/booking-links\nGET/PATCH/DELETE /api/booking-links/:id\nGET/POST /api/appointments\nGET/PATCH/DELETE /api/appointments/:id\nGET /api/public/booking-links/:slug\nPOST /api/public/appointments`}</code></pre></div></section></main>;
}
function DashboardPreview({agenda}:{agenda: typeof demoAppointments}){return <div id="demo" className="rounded-3xl border border-zinc-200 bg-white p-4 shadow-soft dark:border-zinc-800 dark:bg-zinc-900"><div className="mb-4 flex items-center justify-between"><Logo compact/><span className="rounded-full bg-atto-red/10 px-3 py-1 text-sm font-bold text-atto-red">Live</span></div><Agenda compact agenda={agenda}/></div>}
function Agenda({compact=false,agenda}:{compact?:boolean;agenda: typeof demoAppointments}){return <div className="rounded-2xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><div className="mb-4 flex items-center gap-2"><BarChart3 className="text-atto-red"/><h3 className="font-bold">Próximas visitas</h3></div><div className="space-y-3">{agenda.slice(0,compact?3:6).map((a,i)=><div key={`${a.time}-${a.client}-${i}`} className="grid grid-cols-[70px_1fr_auto] items-center gap-3 rounded-xl border border-zinc-100 p-3 dark:border-zinc-800"><strong>{a.time}</strong><div><p className="font-semibold">{a.client}</p><p className="text-sm text-zinc-500">{a.consultant} · {a.origin}</p></div><span className="rounded-full bg-zinc-100 px-3 py-1 text-xs dark:bg-zinc-800">{a.status}</span></div>)}</div></div>}
function StatusPanel({statuses}:{statuses?: {status:string;count:number}[]}){return <div className="rounded-2xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><h3 className="mb-4 font-bold">Agendamentos por status</h3>{(statuses?.length ? statuses : [{status:'scheduled',count:12},{status:'confirmed',count:8},{status:'cancelled',count:2}]).map((item)=><div key={item.status} className="mb-3 flex items-center justify-between"><span>{item.status}</span><strong>{item.count}</strong></div>)}</div>}
function Feature({icon:Icon,title,text}:{icon: ElementType,title:string,text:string}){return <div className="rounded-2xl border border-zinc-200 bg-white p-6 shadow-sm dark:border-zinc-800 dark:bg-zinc-900"><Icon className="mb-4 text-atto-red"/><h3 className="text-xl font-black">{title}</h3><p className="mt-2 leading-7 text-zinc-600 dark:text-zinc-300">{text}</p></div>}
