import { cleanOptional, cleanText } from '@/lib/security/sanitize';
import { getAvailableSlots } from '@/lib/availability';
import { confirmationMessage } from '@/lib/notifications';
import { createAppointment as storageCreateAppointment, createAuditLog, createClient, createNotificationLog, findClientByPhone, getBookingLinkBySlug, updateAppointment as storageUpdateAppointment } from '@/lib/storage';
import type { z } from 'zod';
import type { createAppointmentSchema, updateAppointmentSchema } from '@/lib/validation/appointment';
type CreateAppointment = z.infer<typeof createAppointmentSchema>; type UpdateAppointment = z.infer<typeof updateAppointmentSchema>;
function addMinutes(date: Date, minutes: number) { return new Date(date.getTime()+minutes*60000); }
export async function createAppointment(input: CreateAppointment, companyId?: string) { const startsAt=new Date(input.startsAt); if(startsAt<=new Date()) throw new Error('Escolha uma data futura.'); const link=input.slug?await getBookingLinkBySlug(input.slug):null; if(!link || (companyId && link.companyId!==companyId)) throw new Error('Link de agendamento não encontrado.'); const date=startsAt.toISOString().slice(0,10), startTime=startsAt.toISOString().slice(11,16); const availability=await getAvailableSlots(link.slug,date); if(!availability.slots.includes(startTime)) throw new Error('Horário indisponível.'); const phone=cleanText(input.client.phone,30); if(!/^\+?[0-9() .-]{8,30}$/.test(phone)) throw new Error('Telefone inválido.'); const client=await findClientByPhone(link.companyId,phone) ?? await createClient({companyId:link.companyId,name:cleanText(input.client.fullName,160),fullName:cleanText(input.client.fullName,160),phone,email:cleanOptional(input.client.email,160),cpf:cleanOptional(input.client.cpf,14)}); const end=addMinutes(startsAt,Number(link.durationMinutes??link.duration??30)); const appointment=await storageCreateAppointment({companyId:link.companyId,bookingLinkId:link.id,consultantId:link.userId,userId:link.userId,clientId:client.id,clientName:client.name??client.fullName,clientPhone:phone,clientEmail:client.email??'',clientCpf:client.cpf??'',date,startTime,endTime:end.toISOString().slice(11,16),startsAt:startsAt.toISOString(),endsAt:end.toISOString(),address:link.address,source:link.slug,notes:cleanOptional(input.notes,600)}); await createAuditLog({companyId:link.companyId,entityType:'Appointment',entityId:appointment.id,action:'appointment.created',metadata:{protocol:appointment.protocol}}); const msg=confirmationMessage({company:link.name,consultant:link.title,date:startsAt,address:link.address,protocol:appointment.protocol}); await createNotificationLog({companyId:link.companyId,appointmentId:appointment.id,channel:'whatsapp',type:'confirmation',status:'pending',payload:{message:msg}}); return { ...appointment, startsAt, endsAt:end, client, bookingLink:link }; }
export async function updateAppointment(idOrProtocol: string, _companyId: string, input: UpdateAppointment) { return storageUpdateAppointment(idOrProtocol, { ...input, ...(input.startsAt?{date:input.startsAt.slice(0,10),startTime:input.startsAt.slice(11,16),status:input.status??'rescheduled'}:{}) }); }
export async function cancelAppointment(idOrProtocol: string, companyId: string) { const updated=await storageUpdateAppointment(idOrProtocol,{status:'cancelled'}); await createAuditLog({companyId,entityType:'Appointment',entityId:idOrProtocol,action:'appointment.cancelled'}); return updated; }
