import { cleanOptional, cleanText } from '@/lib/security/sanitize';
import { createAuditLog, createBookingLink, getBookingLinkBySlug as storageGetBySlug, listAppointments, updateBookingLink as storageUpdateBookingLink } from '@/lib/storage';
import type { z } from 'zod';
import type { createBookingLinkSchema, updateBookingLinkSchema } from '@/lib/validation/booking-link';
type CreateBookingLinkInput = z.infer<typeof createBookingLinkSchema>; type UpdateBookingLinkInput = z.infer<typeof updateBookingLinkSchema>;
export function toCreateBookingData(input: CreateBookingLinkInput, companyId: string) { return { companyId, userId: input.userId, slug: cleanText(input.slug.toLowerCase(),80), name: cleanText(input.name,120), title: cleanOptional(input.title,120), description: cleanOptional(input.description,500), address: cleanText(input.address,240), duration:Number(input.duration), durationMinutes:Number(input.duration), dailyLimit:Number(input.dailyLimit), availableDays:input.availableDays, availableSlots:input.availableSlots, isActive:input.isActive??true, logoUrl:input.logoUrl, bannerUrl:input.bannerUrl, consultantPhotoUrl:input.consultantPhotoUrl, primaryColor:input.primaryColor, buttonColor:input.buttonColor, backgroundColor:input.backgroundColor, textColor:input.textColor, welcomeText:cleanOptional(input.welcomeText,600), confirmationText:cleanOptional(input.confirmationText,600) }; }
export function toUpdateBookingData(input: UpdateBookingLinkInput) { return Object.fromEntries(Object.entries(input).filter(([,v])=>v!==undefined)); }
export async function writeAudit(companyId: string, action: string, entity: string, entityId: string, metadata?: unknown) { await createAuditLog({ companyId, action, entityType: entity, entityId, metadata }); }
export async function getPublicBookingLink(slug: string) { return storageGetBySlug(slug); }
export async function saveBookingLink(input: CreateBookingLinkInput, companyId: string) { const link=await createBookingLink(toCreateBookingData(input, companyId)); await writeAudit(companyId,'booking_link.created','BookingLink',link.id,{slug:link.slug}); return link; }
export async function patchBookingLink(id:string, companyId:string, input:UpdateBookingLinkInput){const link=await storageUpdateBookingLink(id,toUpdateBookingData(input)); if(link) await writeAudit(companyId,'booking_link.updated','BookingLink',id,{}); return link;}
export async function publicLinkDto(link: any) { const appointments=await listAppointments(link.companyId); return { id:link.id, slug:link.slug, name:link.name, description:link.description, imageUrl:link.imageUrl, address:link.address, duration:Number(link.durationMinutes??link.duration??30), dailyLimit:Number(link.dailyLimit??99), availableDays:Array.isArray(link.availableDays)?link.availableDays:[], availableSlots:Array.isArray(link.availableSlots)?link.availableSlots:[], company:{name:link.companyName??'ATTO AGENDA',slug:link.companyId}, consultant:{name:link.title??link.name,title:'Consultor comercial',avatarUrl:link.consultantPhotoUrl}, appearance:{ title:link.title, consultantPhotoUrl:link.consultantPhotoUrl, bannerUrl:link.bannerUrl, logoUrl:link.logoUrl, primaryColor:link.primaryColor??'#ed1c24', buttonColor:link.buttonColor??'#ed1c24', backgroundColor:link.backgroundColor??'#ffffff', textColor:link.textColor??'#09090b', theme:link.theme??'auto', layout:link.layout??'side', welcomeText:link.welcomeText, confirmationText:link.confirmationText, instructions:link.instructions }, reservedSlots:appointments.filter((a:any)=>a.bookingLinkId===link.id&&a.status!=='cancelled').map((a:any)=>`${a.date}T${a.startTime}:00.000Z`) }; }
